### ISSUE TITLE
Write metadata to multiple files at once

### ISSUE THREAD

**Issue by jfml** [comictagger/comictagger#181] opened 2021-01-05 09:52 UTC
Not sure if this would be possible but if you have a series it would be super awesome if you could edit artist, writer, publisher etc. for all issues at once. Keep up the good work! ^__^

**Comment by jwmcdermaid** [comment] 2021-01-05 22:18
I agree with this, it would be extremely useful, if possible of course.

On Jan 5, 2021, at 2:53 AM, jfml <notifications@github.com> wrote:

﻿

Not sure if this would be possible but if you have a series it would be super awesome if you could edit artist, writer, publisher etc. for all issues at once. Keep up the good work! ^__^

**Comment by lordwelch** [comment] 2022-06-08 04:08
closing this as a duplicate of  #23

**Closed as completed by lordwelch** 2022-06-08 04:08 UTC
Labels: feature-request
