### ISSUE TITLE
Error when tagging

### ISSUE THREAD

**Issue by IDontKnow218** [comictagger/comictagger#560] opened 2023-10-29 17:50 UTC
![image](https://github.com/comictagger/comictagger/assets/72819892/90f6b183-2e8d-4aaf-aa21-6a964f8f0d26)

I keep getting this when I'm trying to tag any .cbz file. Fix?

**Comment by dlovingood** [comment] 2023-10-30 22:53
I'm seeing the same error on the macOS version.

**Comment by lordwelch** [comment] 2023-10-31 03:24
I can't reproduce the issue, but it looks like whatever comics you're trying to tag don't have covers on comicvine yet

**Comment by IDontKnow218** [comment] 2023-10-31 03:39
> I can't reproduce the issue, but it looks like whatever comics you're trying to tag don't have covers on comicvine yet

The stuff I was tagging had covers in Comicvine. Anyways, the error fixed itself for some reason.

**Comment by dlovingood** [comment] 2023-10-31 18:22
Same for me. Might have been comicvine connectivity issues (timeouts).

**Comment by allanabiud** [comment] 2023-11-02 09:58
I'm also having the same issue
![comictagger_wEbbcXngPl](https://github.com/comictagger/comictagger/assets/66108188/44fb7a4e-457f-44a4-a2c2-2cbe65240a51)

**Comment by lordwelch** [comment] 2023-11-02 19:21
I can't do anything without a log or a comic that can consistently re-produce the issue

**Comment by allanabiud** [comment] 2023-11-03 13:22
> I can't do anything without a log or a comic that can consistently re-produce the issue

It started working fine again, so I don't know what was happening

**Comment by laxtrey5** [comment] 2023-11-04 18:56
I also have had the same issue come up, on and off over the past week or so. It does not consistently happen for the same comic each time

![image](https://github.com/comictagger/comictagger/assets/149900717/f19cc5d8-485e-407d-893b-c539f75d52f7)

**Comment by lordwelch** [comment] 2023-11-04 19:13
@laxtrey5 your issue is completely separate, and is probably fixed in the latest alpha, but I'll have to check

**Comment by lordwelch** [comment] 2024-02-25 03:14
If this happens again open a new issue

**Closed as not planned by lordwelch** 2024-02-25 03:14 UTC
