### ISSUE TITLE
"Save Tags" remove any text formatting from "Auto-Tag"

### ISSUE THREAD

**Issue by nuclearedc** [comictagger/comictagger#614] opened 2024-02-26 23:32 UTC
When using the "Auto-Tag" feature, the "ComicInfo.xml" file that is created will have the text formatting from ComicVine.
![Screenshot 2024-02-26 152019](https://github.com/comictagger/comictagger/assets/161392198/0aff38c6-b196-4f56-adae-dbdfea215d10)

However, if I would manually edit (to correct a typo or add information) and then save/update the tag using the "Save Tags" button, all of the text formatting get converted to plain text.
![Screenshot 2024-02-26 152236](https://github.com/comictagger/comictagger/assets/161392198/a90cd2ce-8afd-4cc7-b81f-b3b433f9a62f)

It seems that saving tags using the "Save Tags" button will remove all the formatting attributes "< /i >< /p >< h2 > etc."
![Screenshot 2024-02-26 152917](https://github.com/comictagger/comictagger/assets/161392198/b8bdf0d0-82de-4e80-88ef-36dee1332a16)

**Comment by lordwelch** [comment] 2024-02-26 23:58
It's not valid to have html tags inside of an xml document. I'm surprised it doesn't just give an error when loading. I have no plans to support text formatting inside of the summary or notes field. It was a bug that it allowed formatting at all and it has been fixed in 14ce8a759f629a22ee5a3e9561bb50e3a92af658

**Closed as completed by lordwelch** 2024-02-26 23:58 UTC

**Comment by nuclearedc** [comment] 2024-02-27 00:11
No problem.
Thank you for the quick reply and totally understand if there is no plans to support text formatting.

Having the formatting made it a bit easier to read the metadata on third party software such as YACreader especially when there are detailed chapter titles:
Without text formatting:
![Screenshot 2024-02-26 160650](https://github.com/comictagger/comictagger/assets/161392198/f6652369-3e3b-423d-930d-7c47cf0d29ad)

With text formatting:
![Screenshot 2024-02-26 160745](https://github.com/comictagger/comictagger/assets/161392198/cff214e8-126a-48fe-bfcb-8b29315e5e55)

**Comment by lordwelch** [comment] 2024-02-27 00:29
Part of the problem is that Qt (the GUI system CT uses) allows a certain amount of html in it's text edit controls and it was rendering the html you had in the description field. In the next alpha it should just show you the raw html, and when saving the html should get escaped properly.
