### ISSUE TITLE
Anansi Project: Schema v2.1: Tags

### ISSUE THREAD

**Issue by MichaelFitzurka** [comictagger/comictagger#260] opened 2022-04-07 17:46 UTC
See https://github.com/comictagger/comictagger/issues/219

We already have this really, on the Other tab, Other Tags field, which is unused for ComicRack style.
It's a string of CSV with no ComicVine import.

**Comment by lordwelch** [comment] 2022-04-15 08:54
I am closing this as a duplicate of #219

**Closed as completed by lordwelch** 2022-04-15 08:54 UTC
