### ISSUE TITLE
How to setup a scrape delay

### ISSUE THREAD

**Issue by typo2014** [comictagger/comictagger#677] opened 2024-09-03 19:13 UTC
Hi 

I really prefer comictagger over comicrack comicvine scrapper but there is a great feature that i'm maybe just dont know how to setup 

With comicrack i can setup a scrape delay of eg. 30 seconds which leads to not hitting the api limits of comicvine - 
with comictagger i hit the limit pretty soon and then run into network errors and no scrapping 

my goal would be to let comictagger run over my folder of 20K comics and tag all of them (or at least the once it can identify) 
currently i run it multiple times a day whenever i have time & think about it 

Maybe there is a better approach i'm not aware 

all the best

**Comment by lordwelch** [comment] 2024-09-03 19:20
The problem is they've started enforcing their limit of 200 requests per hour, which means you're limited to a max of tagging 200 comics per hour. So you are looking at two days no matter what. I plan on improving the current rate limiter to account for the change

**Comment by typo2014** [comment] 2024-09-03 19:29
the 2 days are fine by me - i know that it wont get faster but i would have to start the program only once and keep it running in the backround 

so e.g. i could let it run over night and (best case) tag 1600 comics per 8 hours sleep 

currently i manage about 3-400 a day and none at night - so everything above that would be a great improvement

**Comment by lordwelch** [comment] 2024-09-12 20:58
Fixed in c9c0c99a2a5b9f308fe5605c66b163b7d995d99c

**Closed as completed by lordwelch** 2024-09-12 20:58 UTC
